# Generated by Django 3.0.8 on 2020-07-14 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('tag_name', models.CharField(max_length=10, verbose_name='Tag_Name')),
                ('min_amount', models.FloatField(verbose_name='Min_Amount')),
                ('man_amount', models.FloatField(verbose_name='Max_Amount')),
                ('enable', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(1, 'crypto'), (2, 'bank'), (3, 'payment_system')])),
            ],
        ),
        migrations.CreateModel(
            name='TargetCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('tag_name', models.CharField(max_length=10, verbose_name='Tag_Name')),
                ('min_amount', models.FloatField(verbose_name='Min_Amount')),
                ('man_amount', models.FloatField(verbose_name='Max_Amount')),
                ('enable', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(1, 'crypto'), (2, 'bank'), (3, 'payment_system')])),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Give_Amount')),
                ('rate', models.FloatField(verbose_name='Rate')),
                ('fee', models.FloatField(verbose_name='Exchange_Fee')),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testAPI.SourceCurrency', verbose_name='Give')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testAPI.TargetCurrency', verbose_name='Get')),
            ],
        ),
    ]
