# Generated by Django 3.0.8 on 2020-07-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcecurrency',
            old_name='man_amount',
            new_name='max_amount',
        ),
    ]
